Step1.
NumPyをインポートするコードを記述する

Step2.
AとBの行列を格納する多次元配列のコードを記述する

Step3.
行列の積の計算をするコードを記述する

Step4.
Step3.の計算結果を表示するコードを記述する

Step5.
行列の要素の最大値を求めるコードを記述する

In [15]:
#Step1. NumPyをインポートするコードを記述する
import numpy as np

#Step2. AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#Step3. 行列の積の計算をするコードを記述する
AB_multi = np.dot(A, B)

#Step4. Step3.の計算結果を表示するコードを記述する
print(AB_multi)

#Step5. 行列の要素の最大値を求めるコード＆最大値を表示するコードを記述する
AB_max = AB.max()
print(AB_max)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
